### ISSUE TITLE
Improving the frontend sidebar

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#168]
This customer request makes sense. They want a way to organize the listing of projects in the frontend sidebar.

"Is there a way to have our project in alphabetical order? Right now it is starting with Z and moving to A"

**Comment by upstreamplugin** [comment]
One more vote this this: 
"Is it possible to reorder Projects for Users on the overall view? Pulling some projects to the top might be useful."

**Comment by upstreamplugin** [comment]
Maybe let's put this to one side until Gutenberg is closer. It may be that we stop using a frontend theme with a sidebar.

**Comment by stevejburge** [comment]
We probably need some pagination at least in the left-sidebar. Either that or we remove the project list from the left sidebar.

Here's just 50% of one user's sidebar:
![screen shot 2018-06-04 at 1 39 36 pm](https://user-images.githubusercontent.com/3868028/40932631-fde28ae6-67fc-11e8-9740-a4d597153680.png)

![screen shot 2018-06-04 at 1 39 48 pm](https://user-images.githubusercontent.com/3868028/40932640-02f18dd4-67fd-11e8-95fc-5718147cc32b.png)

![screen shot 2018-06-04 at 1 40 04 pm](https://user-images.githubusercontent.com/3868028/40932644-052ff4c8-67fd-11e8-8084-148374029238.png)
