### ISSUE TITLE
Include some subtle ads for Upgrades and reviews

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#184]
Some ideas for the free version ...

A small link on the plugins page:
![screen shot 2017 10 03 at 7 21 00 am](https://user-images.githubusercontent.com/26938537/31123146-ac52efa0-a80c-11e7-8d97-65882cd38878.png)

An ad and newsletter box on the settings page:
![screen shot 2017-10-03 at 7 22 50 am](https://user-images.githubusercontent.com/26938537/31123144-ac3332f0-a80c-11e7-977f-7b5e4e319a84.png)

**Comment by upstreamplugin** [comment]
Perhaps include a "Copy" link under projects, with a small suggestion to upgrade

**Comment by stevejburge** [comment]
Perhaps a third idea here: reviews https://freemius.com/blog/how-we-increase-our-wordpress-plugin-reviews-by-700-percent/
![mashshare-review-notice](https://user-images.githubusercontent.com/3868028/41739982-bd2134ec-7564-11e8-870d-b75e262e0381.png)

In UpStream, we could trigger reviews after someone has created 5 projects?

**Comment by stevejburge** [comment]
Finally, we can improve the extensions page

![extensions](https://user-images.githubusercontent.com/3868028/41740437-02111e90-7566-11e8-8be6-9b72c56065f3.png)

Odd spacing on big screens:

![screen shot 2018-06-21 at 3 16 10 pm](https://user-images.githubusercontent.com/3868028/41740451-122dea06-7566-11e8-8335-254420c980a7.png)

Use a colorful link like this?
![screen shot 2018-06-21 at 3 17 14 pm](https://user-images.githubusercontent.com/3868028/41740492-35c14ada-7566-11e8-9906-00c595e9d809.png)

**Comment by andergmartins** [comment]
Sub-tasks:

- [ ] Add color to the submenu
- [ ] Upgrade link in the plugin actions
- [ ] Improve extensions page
- [ ] Ad and newsletter box on the settings page
- [ ] Ask for reviews
