### ISSUE TITLE
Improve Tasks and Bugs pages

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#208]
Let's add some normal WordPress features to the Tasks and Bugs pages

We can make it more like the normal "Posts" and "Pages:

- "Add New"
- Bulk actions
- Links under each item

![screen shot 2017 10 29 at 10 46 29 am 1](https://user-images.githubusercontent.com/26938537/32144926-ee86f760-bc96-11e7-814a-85605958889b.png)

**Comment by upstreamplugin** [comment]
One thing to note ... "Tasks" and "Bugs" only appear if you have Tasks or Bugs assigned to you.

We can consider making them permanent menu links

**Comment by stevejburge** [comment]
Closed in favor of frontend improvements: https://github.com/AllediaWordPress/UpStream/issues/418
