### ISSUE TITLE
Expose an "assign_project_tasks" permission

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#314]
"I started building Projects with my people, and discovered an issue. How do I assign Tasks or Bugs to a Client User? They don't appear in the list. I've read through the documentation and noted at least two places where it referenced assigning Tasks to Client Users, but I don't know which permission to grant them to allow it."

Can we expose permissons to allow UpStream members to:
- assign tasks to others
- have tasks assigned to them

FWIW, as we go along, it would be good to expose as many different permissions as possible. I'm recommending that people interact with them using the Members plugin https://upstreamplugin.com/docs/customizing-permissions-upstream/

**Comment by upstreamplugin** [comment]
Related to this, it used to be possible to make a Client User into the Project Owner. That's no longer possible.

**Comment by upstreamplugin** [comment]
Here's the use-case which is very valid:

> Our customer must provide us with pictures and other documentation to begin the project. Is this something that will be available soon?

**Comment by stevejburge** [comment]
Solved in 1.22
