### ISSUE TITLE
Permissions extension

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#327]
I'm really starting to think we need a Permissons extension for UpStream

We get a *lot* of permission requests.

It would most likely be a series of checkboxes like this, although it would also involve "Guest" users who don't have a WP account
![permissions-view](https://user-images.githubusercontent.com/26938537/35512788-f3c0dcde-04ce-11e8-81cb-2e9fa4c05b68.png)

**Comment by upstreamplugin** [comment]
Feedback from a user on permissions:

"I work with freelancers day in, day out and I want them to respond via comments only and not have the ability to edit the task (or anything that I have entered)."

**Comment by upstreamplugin** [comment]
Here's a similar take from a different angle ...

"I want users to be able to edit their own tasks, but not other tasks. If they are not assigned to a task, the edit button should be hidden."

**Comment by upstreamplugin** [comment]
More on this here: https://github.com/upstreamplugin/UpStream/issues/314

That user wanted the ability to control who can create and assign tasks

**Comment by upstreamplugin** [comment]
Another user wanted to give Client Users the ability to create projects for themeselves

**Comment by stevejburge** [comment]
Another customer ...
"I want to make some files read only i.e. no one can delete or modify those."

**Comment by stevejburge** [comment]
Let's skip this and focus on exposing permissions for other extensions
