### ISSUE TITLE
Project progress broken without milestones

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#346]
> For my workflow, I do not need Milestones so I disabled them (General -> Disable Milestones). By doing so, the Project progress went broken. Progress in Tasks is no longer affecting the overall progress of the Project and it is always 0%. It seems as if Project's progress is calculated only through Milestones and once Milestones are disabled,then Task progress have no effect on Project's overall progress. 

Should we calculate project progress directly from Tasks? Milestones don't have their own progress bars so should be ignored

**Comment by deenison** [comment]
hm, seems like a design flaw. 
100% agree on base the overall progress via Tasks only.

**Comment by stevejburge** [comment]
Closed in favor of https://github.com/AllediaWordPress/UpStream/issues/387
