### ISSUE TITLE
Calendar View loads very slowly on long selections

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#414]
Choose a high number such as "10 weeks" or "12 weeks" and the Calendar View just spins and spins.

BTW, we offer 12 weeks via the admin, but only 10 weeks on the frontend.

![screen shot 2018-03-12 at 11 12 52 am](https://user-images.githubusercontent.com/26938537/37292022-5dcf3bf6-25e6-11e8-9a4e-0f624846ea5d.png)

**Comment by upstreamplugin** [comment]
Related problem
- Find a month that has tasks, for example, June
- Choose that month
- The Calendar just spins with the "Loading" message

![screen shot 2018-03-17 at 2 03 04 pm](https://user-images.githubusercontent.com/26938537/37558554-ee7fecc8-29eb-11e8-8072-1a5a37576181.png)

**Comment by stevejburge** [comment]
Fixed
