### ISSUE TITLE
Be more flexible with media library access

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#451]
So by default, users are restricted to accessing only their files:
https://upstreamplugin.com/docs/media-library/

This is a good security feature, but can be a problem for some people including Site Administrators.

We should consider making this a checkbox Enable/Disable feature, or perhaps exposing it as a permissions so it can be applied only to certain roles.

**Comment by andergmartins** [comment]
Duplication of https://github.com/AllediaWordPress/UpStream/issues/548.
