### ISSUE TITLE
Discussion link still appears in sidebar despite being disabled

### ISSUE THREAD

**Issue by stevejburge** [AllediaWordPress/UpStream#472]
![discussion-link](https://user-images.githubusercontent.com/3868028/40075542-85eb8b44-584a-11e8-9b98-b10a5f457bab.png)

**Comment by andergmartins** [comment]
Fixed on https://github.com/AllediaWordPress/UpStream/commit/e1690bf23f63c6c3da2e3c0fbefe033d25072ab3
