### ISSUE TITLE
Comments are plain text with HTML tags

### ISSUE THREAD

**Issue by stevejburge** [AllediaWordPress/UpStream#545]
> When I add comments to a project the email it sends receives as plain text with html tags. Any idea what I'm doing wrong.

![screen-shot-2018-06-13-at-10-20-52-am](https://user-images.githubusercontent.com/3868028/41410691-47f48636-6fa8-11e8-9cbd-0b72039b7085.png)
![screen-shot-2018-06-13-at-10-22-33-am](https://user-images.githubusercontent.com/3868028/41410692-48045598-6fa8-11e8-8fbd-50039f956bc8.png)

**Comment by andergmartins** [comment]
@stevejburge WordPress uses plain text for comments and it tries to sanitize the comments we send with HTML, but it removes paragraphs and line breaks. I think we should use plain text for comments on projects as well.

**Comment by b-trav** [comment]
Hi @andergmartins, can you clarify - are you suggesting removing the ability to add links in a comment? This would seem a step backwards to me. Most WordPress themes allow links in comments, don't they?

**Comment by andergmartins** [comment]
Hi @b-trav yes, but probably not for all users. Maybe I add a check for the capability "unfiltered_html". If the user has it, we will try to keep the HTML in the comments. If not, it should not allow adding HTML in comments.

**Comment by andergmartins** [comment]
I have worked in a fix for this. Since we use WordPress' comment system, we detect if the comment is coming from a project, then change the content type to HTML and convert the text and links to HTML content in the email. This is useful to fix another issue related to images in comments. If we don't use HTML, we can't display the image in the e-mail.

**Comment by andergmartins** [comment]
Here is a beta package, for testing the fix:

[upstream-1.20.3-beta.2.zip](https://github.com/AllediaWordPress/UpStream/files/2330492/upstream-1.20.3-beta.2.zip)
