### ISSUE TITLE
Media Upload in Grid View only shows images uploaded by the current user

### ISSUE THREAD

**Issue by b-trav** [AllediaWordPress/UpStream#548]
When UpStream plugin is activated, if an administrator goes to Dashboard ->Media -> Library (grid view) they only see the images uploaded by the current user. Clicking on "list view" show all images in the media library.

This bug is significant because when inserting an image into a post or page "grid view" is the only option available.

deactivating the UpStream plugin returns the Media Library to the normal (correct) state.

**Comment by stevejburge** [comment]
Thanks @b-trav. This was a design decision made early in life of this plugin. There's some details on it here: https://upstreamplugin.com/docs/media-library/

However, I think you're right. We should leave the media library in it's normal state, then allow UpStream users to add restrictions if needed.

**Comment by b-trav** [comment]
I have managed to fix this bug in my plugin by commenting out a few lines from `includes/admin/class-up-admin.php`, as per below, but it would be nice to get this fixed in the official code.
```
    /**
     * Only show current users media items
     *
     */
    public function filter_user_attachments( $query = [] ) {
        /*
        $user_id = get_current_user_id();
        if ( $user_id ) {
            $query['author'] = $user_id;
        }
        */
        return $query;
    }
```

**Comment by stevejburge** [comment]
Thanks @b-trav Perhaps we can make that into a configurable setting in the admin

**Comment by andergmartins** [comment]
Fixed adding a config option to select what roles can see unfiltered attachments.

<img width="1280" alt="upstream_ _tests_ _wordpress" src="https://user-images.githubusercontent.com/407131/42348338-76e90196-807f-11e8-81b9-353cf441c8c8.png">
