### ISSUE TITLE
Toggle Filters don't work for new status

### ISSUE THREAD

**Issue by b-trav** [AllediaWordPress/UpStream#563]
At `wp-admin/admin.php?page=upstream_tasks` I created a new status called "WaitingFor". If I go to the front-end of a project, I can see tasks with status "WaitingFor" there, but if I filter status by "WaitingFor" the tasks disappear until I turn the filter off.

**Comment by b-trav** [comment]
Actually, on the front end "toggle filters" does not work for anything other than "None". If I select "Closed" I see no tasks, even though I have a bunch of closed tasks. Same with all the other statuses.

**Comment by stevejburge** [comment]
One more report of this from a customer. It works for Projects, but is broken for Tasks.

**Comment by stevejburge** [comment]
Same customer:

> Just come across another filtering bug - this time in the WordPress Tasks panel. Attempts to filter by project result in a blank list.

**Comment by stevejburge** [comment]
Solved in 1.19.1
