### ISSUE TITLE
Custom fields bug with None and the dropdown type

### ISSUE THREAD

**Issue by stevejburge** [AllediaWordPress/UpStream#577]
> I have a custom field type dropdown with three options set - one of which is marked as the default value. But when I create a new task the pre-selected value is None - which isn’t one of the options.
> 
> I did notice somewhere an option to make None available as one of the values. But that wasn’t offered as an option when I added this custom field.

**Comment by andergmartins** [comment]
Well, the commits above are not related only to radio fields. It fixes the issue for select boxes as well.
