### ISSUE TITLE
Add projects from the front-end

### ISSUE THREAD

**Issue by upstreamplugin** [AllediaWordPress/UpStream#62]
We had a request to allow people to create projects via the front-end of the site.

**Comment by upstreamplugin** [comment]
Here's a more detailed list of requirements from a 2nd customer

- add new project
- modify projects
- add and manage project users/clients

**Comment by upstreamplugin** [comment]
One more vote for this from a customer

**Comment by deenison** [comment]
How this feature would affect or be related to the Frontend Edit extension? @upstreamplugin

**Comment by upstreamplugin** [comment]
Perhaps a new extension, or a new core feature then?

**Comment by deenison** [comment]
As you suggested on #188, I agree that this would be a great addition to Frontend Edit instead of a separated extension.

**Comment by upstreamplugin** [comment]
We have another customer request for this today

**Comment by upstreamplugin** [comment]
We had another customer request for this today

**Comment by upstreamplugin** [comment]
We had yet another customer request for this today @deenison

**Comment by upstreamplugin** [comment]
Another request: "I've been using Podio from about the day it was released and Basecamp prior to that. Why, as admin, do I have to jump back into the backend to add a project?"

**Comment by muff1n** [comment]
Any progress on this? We're getting anxious. :)

**Comment by upstreamplugin** [comment]
Hi @muff1n. Yes, we're 100% on this. Sorry for the delay. It's the top item on our to-do list.

**Comment by stevejburge** [comment]
One more vote: 

> I was wondering if there was a way to submit, through a form, or the front end editor extension, a new project. I'm trying to make it easy for, say, a customer to submit a new project and have it go right into Upstream without having to go into the Wordpress backend.

**Comment by stevejburge** [comment]
OK, time to do this.

**Comment by stevejburge** [comment]
We've got feedback from half-a-dozen people so far. At least 4 want to give the Clients the ability to create projects. 1 says "no way" to that. 

So we'll need some permission control.

It may also make sense to re-use this "New Project" form for editing existing project details.

**Comment by stevejburge** [comment]
Some of the feedback so far:

User 1:
> Projects should be created by managers, supervisors and designated staff (in the long run clients may create projects). The managers can be given all privileges/power regarding the project and possibly the supervisors...the designated staff access can be limited

User 2:
> we only allow administrators to create new projects. What we really want on the front end for the admins to create new projects if for it all to be able to be presented like a form they fill out. Selecting various options from lists, choosing the users who will participate in the project, etc. And then for those users to be able to see and use the prioject.

User 3:
> Hello, I love the idea of letting clients create projects. In our line of work many of the small groups of tasks we perform are more like small projects than they are simple service requests. making small projects out of these requests also helps us review tasks and workflows after the “project” has completed

**Comment by stevejburge** [comment]
This is logically linked to front-end editing https://github.com/AllediaWordPress/UpStream/issues/62

**Comment by stevejburge** [comment]
Related with Clients https://github.com/AllediaWordPress/UpStream/issues/518
