### ISSUE TITLE
Display more information to the plugin row about license status and if there is no license key.

### ISSUE THREAD

**Issue by andergmartins** [AllediaWordPress/UpStream#652]
This will help users to realize if the updates are not displayed because there is no license key, or the license key is not valid.

"UPDATE UNAVAILABLE! Please enter a valid license key to enable automatic updates. Enter License Key"

"You must have a valid subscription in order to get upgrades or support for this plugin. Purchase a subscription or enter an existing site key."

**Comment by stevejburge** [comment]
Fixed in 1.22
